### ISSUE TITLE
Replication/Migration

### ISSUE THREAD

**Issue by bmeck** [dscape/futoncli#12]
Would be nice to have a way to generate a migration plan with the following steps:
1. Replicate to non-used db
2. Run migration
3. Test migration
4. Backup to other db optional
5. Run migration on live db

**Comment by bmeck** [comment]
Working on it : https://github.com/bmeck/futoncli/tree/migrate

**Comment by dscape** [comment]
@bmeck did this ever get to a point where you can merge?

**Comment by dscape** [comment]
@bmeck any news? @julianduque has been cleaning issues like crazy, is this still an issue?

Please do reopen if its the case
